### ISSUE TITLE
Invalid name

### ISSUE THREAD

**Issue by TingPing** [JasonLG1979/gnome-shell-extensions-weather-in-the-clock#1]
`weatherintheclock@github.io`

To my knowledge you don't own the github domain :P

(Useful extension btw, something I've wanted)

**Comment by JasonLG1979** [comment]
Would ```weatherintheclock@JasonLG1979.github.io``` be better?

**Comment by TingPing** [comment]
Yea that is fine.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-weather-in-the-clock/commit/5625730665ac86a68394802031f8593fd2acb83e

Should do it right?

**Comment by JasonLG1979** [comment]
> Useful extension btw, something I've wanted)

I'm not sure why it's not a default option?

**Comment by TingPing** [comment]
Talk to upstream and see if they would be interested?

**Comment by JasonLG1979** [comment]
> Talk to upstream and see if they would be interested?

I just might. I mean really by default detailed weather info is in the menu. I think it makes perfect sense to show what my extension does. Even if it were a hidden feature like the date in the panel.
