### ISSUE TITLE
Change position

### ISSUE THREAD

**Issue by sojusnik** [JasonLG1979/gnome-shell-extensions-weather-in-the-clock#2]
Is it possible to change the position of the weather indicator to the left of the clock?

**Comment by JasonLG1979** [comment]
You can change where they are inserted in the clock by changing the numbers in [these lines](https://github.com/JasonLG1979/gnome-shell-extensions-weather-in-the-clock/blob/master/weatherintheclock%40JasonLG1979.github.io/extension.js#L39-L40). The numbers represent the index at which the icon and label (text) are inserted into the clock. I have no plan to make anything configurable. The point of the extension is to be dead simple. If you'd like a configurable weather extension there are a couple already available.
