### ISSUE TITLE
Weather sometimes doesn't show

### ISSUE THREAD

**Issue by chrisjbillington** [JasonLG1979/gnome-shell-extensions-weather-in-the-clock#3]
## Distro Name & Version
Arch linux, fully updated

## GNOME Shell Version
3.30.2

## Other Installed Extensions
* Launch new instance
* AlternateTab
* User Themes
* Frippery Move Clock
* Impatience
* (K)StatusNotifierItem/AppIndicator Support
* Transparent OSD
* Weather In The Clock
* Arch Linux Updates Indicator
* Bumblebee Status
* Status Area Horizontal Spacing
* system-monitor
* NoAnnoyance
* Panel OSD

## Expected Behavior
The weather should always be present next to the clock

## Current Behavior
Sometimes, the weather is not visible next to the clock

## Detailed Description
I haven't yet noticed a pattern as to when the weather isn't visible, but disabling and re-enabling the extension or restarting gnome shell fixes the problem. I will update this issue if I notice a pattern.

**Comment by JasonLG1979** [comment]
I ran into the same issue when I upgraded to Fedora 29 (also GNOME 3.30) On 28 with GNOME 3.28 I never had any problems.

I'm unsure of the exact cause, but in my case what seemed to help is to turn off automatic location in GNOME Weather and set the location manually. GNOME Weather controls what is shown in the extension.

**Comment by JasonLG1979** [comment]
@chrisjbillington I just updated the master branch with a possible fix to the issue I noticed. If you would give that a test and see if it fixes your issue also. They may be the same.

See the [wiki](https://github.com/JasonLG1979/gnome-shell-extensions-weather-in-the-clock/wiki/Installation) for instructions on how to install.

**Comment by JasonLG1979** [comment]
As a side note, It's nice to see this extension works with the Frippery Move Clock extension. As an extension developer you never know how your extension is going to react to or interact with other extensions. Extensions really are the Wild West. There is no API, extensions are basically Monkey Patches that can do pretty much anything to the Shell.

**Comment by chrisjbillington** [comment]
Thanks for the quick attention! I've updated to master and I'll see how it goes

I tentatively suspect what the pattern might be. It might be when I wake my computer from sleep and it connects to a wifi network that has a login page. So it looks like I have internet, but all http pages are redirecting to the login page and all https are not loadable..

This only comes up once or twice a day because the wifi network in question remembers me unless my laptop has been asleep for a while, so I am not confident that is is the actual cause.

Anyway I'll post here again if I see the problem still or if I have any other thoughts.

**Comment by JasonLG1979** [comment]
Does the weather under the calendar work after you wake your computer?

**Comment by chrisjbillington** [comment]
Yes, it does.

Just woke my computer and I have weather under the calendar but not next to the clock:

![image](https://user-images.githubusercontent.com/1044087/49587987-841de480-f933-11e8-8921-4b8bef3494a1.png)

**Comment by chrisjbillington** [comment]
It's a little annoying that I can only reproduce this once a day or so after a long sleep, otherwise I'd be able to debug better. But I'll turn off automatic location (it was on) and verify if that helps.

**Comment by JasonLG1979** [comment]
The weather info under the calendar is updated when ever you open the date time menu, and since the info is there we know that not being able to get the info isn't the problem. (My extension and the weather under the calendar get their info from the same thing/place.)

I think maybe I have a theory as to what's going on.

**Comment by JasonLG1979** [comment]
@chrisjbillington give master a try again and see if that does it?

**Comment by JasonLG1979** [comment]
Basically my theory is that the 1st weather update after you wake your computer does not contain valid info. (In the case of invalid info the extension is hidden) Before there was a 10 min timeout to update the extension so if the 1st update info was not valid you'd have to wait for either GNOME Weather to change something or another 10 min for anything to show up.

My latest commit uses a much shorter 3 sec initial timeout until valid info shows up and then switches to 10 mins.

**Comment by chrisjbillington** [comment]
Sounds plausible - I'm giving the new master a go and will report back.

**Comment by chrisjbillington** [comment]
It's looking good so far! Have woken my computer about three times after long sleeps and the weather has been visible pretty quickly.

**Comment by chrisjbillington** [comment]
Another few days and this is still looking good.

**Comment by luca-viggiani** [comment]
Hi I'm arch linux too and I'm using latest version from git. Weather does not show neither in the clock nor in the calendar view. Location services are enabled. Looking glass does not show any errors for the extensiona

**Comment by chrisjbillington** [comment]
If the weather does not show in the calendar view, it might not be an issue with this extension. Do you have gnome-weather installed, and does it work?

**Comment by luca-viggiani** [comment]
Hi, sorry I thought I had already answered but probably I forgot to hit "Comment" button.
Yes, it was my fault sorry... I didn't have gnome-weather installed... :(
After installing it, everything worked out of the box.
Just one suggestion: you may want to mention gnome-weather in requirements / installation instruction. I know that it may sound obvious but on gnome extensions site there are other extensions that uses different sources (like yahoo weather etc) and don't require gnome-weather, and this might cause confusion to some users (like me :) ). BTW, it's just a suggestion. Thanks for your work

**Comment by chrisjbillington** [comment]
Since this is solved, could we get a new version released to extensions.gnome.org?
